AWSTemplateFormatVersion: '2010-09-09'
Description: "Managed AWS Config rule (REQUIRED_TAGS) for EC2 Instances with SSM remediation."

Resources:
  # 1) Managed Config rule (no Lambda)
  RequiredTagsRule:
    Type: AWS::Config::ConfigRule
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      ConfigRuleName: OMBASR-ConfigRule-OPS-EC2-RequiredTags
      Description: "Check EC2 Instances for required tags AppCatId and SupportTeam."
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: REQUIRED_TAGS
      InputParameters:
        tag1Key: AppCatId
        tag1Value: UNKNOWN
        tag2Key: SupportTeam
        tag2Value: UNKNOWN

  # 2) Remediation IAM role (dedicated to SSM Automation)
  RemediationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: OMBASR-RemediateRole-OPS-EC2-RequiredTags
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: OMBASR-Remediate-EC2-Tagging
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Tagging perms for EC2 instances
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DeleteTags
                  - ec2:DescribeTags
                  - ec2:DescribeInstances
                Resource: "*"
              # Logging for the automation script
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # 3) SSM Automation document (remediation)
  SetRequiredTagsDoc:
    Type: AWS::SSM::Document
    Properties:
      Name: OMBASR-Remediation-OPS-EC2-RequiredTags
      DocumentType: Automation
      Content:
        schemaVersion: '0.3'
        description: "Add missing required tags (AppCatId, SupportTeam) to an EC2 Instance."
        assumeRole: "{{ AutomationAssumeRole }}"
        parameters:
          AutomationAssumeRole:
            type: String
            description: "IAM role for Automation to perform tagging."
          InstanceId:
            type: String
            description: "Target EC2 instance ID (e.g., i-0abc123...)."
          AppCatId:
            type: String
            default: "UNKNOWN"
          SupportTeam:
            type: String
            default: "UNKNOWN"
        mainSteps:
          - name: EnsureTags
            action: aws:executeScript
            description: "Creates the required tags on the EC2 Instance if missing."
            inputs:
              Runtime: python3.11
              Handler: script_handler
              InputPayload:
                instance_id: "{{ InstanceId }}"
                appcat: "{{ AppCatId }}"
                supteam: "{{ SupportTeam }}"
              Script: |
                import boto3
                ec2 = boto3.client('ec2')

                def script_handler(event, context):
                    instance_id = event['instance_id']
                    appcat = (event.get('appcat') or 'UNKNOWN')
                    supteam = (event.get('supteam') or 'UNKNOWN')

                    # Simply apply the tags (idempotent if already correct)
                    tags = [
                        {'Key': 'AppCatId', 'Value': appcat},
                        {'Key': 'SupportTeam', 'Value': supteam},
                    ]
                    ec2.create_tags(Resources=[instance_id], Tags=tags)
                    return {"changed": True, "instance": instance_id, "tags_applied": tags}

  # 4) Config RemediationConfiguration (wire rule -> SSM document)
  RequiredTagsRemediationInstance:
    Type: AWS::Config::RemediationConfiguration
    Properties:
      ConfigRuleName: !Ref RequiredTagsRule
      ResourceType: AWS::EC2::Instance
      TargetType: SSM_DOCUMENT
      TargetId: !Ref SetRequiredTagsDoc
      TargetVersion: "$DEFAULT"
      Automatic: false          # set to true for auto-remediation
      ExecutionControls:
        SsmControls:
          ConcurrentExecutionRatePercentage: 10
          ErrorPercentage: 10
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values:
              - !GetAtt RemediationRole.Arn
        # Pass the evaluated instance ID to the runbook
        InstanceId:
          ResourceValue:
            Value: RESOURCE_ID
        AppCatId:
          StaticValue:
            Values: ["UNKNOWN"]
        SupportTeam:
          StaticValue:
            Values: ["UNKNOWN"]

Outputs:
  ManagedRuleName:
    Value: !Ref RequiredTagsRule
  RemediationDocumentName:
    Value: !Ref SetRequiredTagsDoc
  RemediationRoleArn:
    Value: !GetAtt RemediationRole.Arn
